# HOST_UID="$(id -u)" HOST_GID="$(id -g)" docker-compose -f ./docker-compose-multirepo-build.yaml up --build
version: "2.4"
services:
  docs:
    build:
      context: .
      dockerfile: docs.build.dockerfile
    volumes:
      - .:/main
    user: '${HOST_UID}:${HOST_GID}'
    command:
      - bash
      - -c
      - |
        pwd
        git init
        git submodule init
        git submodule update
        git submodule foreach git pull origin gh-pages
        # tail -f /dev/null
